# Generated by Django 6.0.4 on 2026-04-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceBrokingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('active_normal', 'Active - Normal Policy Cleared'), ('inactive', 'Inactive'), ('lapsed', 'Lapsed')], default='active_normal', max_length=50)),
                ('dep_code', models.CharField(max_length=20, verbose_name='Dep. Code')),
                ('ack_date', models.DateField(verbose_name='Ack Date')),
                ('p_date', models.DateField(verbose_name='PDate')),
                ('login_date', models.DateField(verbose_name='Login Date')),
                ('ack_no', models.CharField(max_length=50, verbose_name='Ack No.')),
                ('ack_verified', models.BooleanField(default=False, verbose_name='Ack is Verified')),
                ('staff_code_no', models.CharField(blank=True, max_length=10, verbose_name='Staff Code No')),
                ('staff_code_name', models.CharField(max_length=100, verbose_name='Staff Name')),
                ('branch_mgr_code', models.CharField(blank=True, max_length=10, verbose_name='Branch Mgr Code')),
                ('branch_mgr_name', models.CharField(max_length=100, verbose_name='Branch Manager')),
                ('branch_assist_code', models.CharField(blank=True, max_length=10, verbose_name='Branch Assist Code')),
                ('branch_assist_name', models.CharField(max_length=100, verbose_name='Branch Assistant')),
                ('exec_code_no', models.CharField(blank=True, max_length=10, verbose_name='Exec. Code No')),
                ('exec_code_name', models.CharField(max_length=100, verbose_name='Executive Name')),
                ('application_no', models.CharField(max_length=30, verbose_name='Application No')),
                ('appln_date', models.DateField(verbose_name='Application Date')),
                ('life_assured', models.CharField(max_length=100, verbose_name='Life Assured')),
                ('policy_no', models.CharField(max_length=30, unique=True, verbose_name='Policy No.')),
                ('policy_date', models.DateField(verbose_name='Policy Date')),
                ('policy_name', models.CharField(max_length=200, verbose_name='Policy Name')),
                ('policy_amt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Policy Amount')),
                ('premium_amt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Premium Amount')),
                ('payment_term', models.PositiveIntegerField(verbose_name='Payment Term (Years)')),
                ('dep_name', models.CharField(max_length=100, verbose_name='Depositor Name')),
                ('address_line1', models.CharField(max_length=200, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2 (PO)')),
                ('address_line3', models.CharField(blank=True, max_length=200, verbose_name='Address Line 3')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('pin', models.CharField(max_length=10, verbose_name='PIN Code')),
                ('mobile_number', models.CharField(blank=True, max_length=15, verbose_name='Mobile Number')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('nominee_name', models.CharField(max_length=100, verbose_name='Nominee Name')),
                ('nominee_dob', models.DateField(verbose_name='Nominee Date of Birth')),
                ('nominee_email', models.EmailField(blank=True, max_length=200, verbose_name='Nominee Email ID')),
                ('nominee_mobile', models.CharField(max_length=15, verbose_name='Nominee Mobile Number')),
                ('company', models.CharField(default='ICICI PRUDENTIAL LIFE INSURANCE COMPANY LIMITED', max_length=200)),
                ('branch_city', models.CharField(default='KODUNGALLUR', max_length=100, verbose_name='City')),
                ('branch_name', models.CharField(default='KODUNGALLUR', max_length=100, verbose_name='Branch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurance Broking Entry',
                'verbose_name_plural': 'Insurance Broking Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
