# Generated by Django 6.0.4 on 2026-05-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancebrokingentry',
            name='appln_date',
        ),
        migrations.RemoveField(
            model_name='insurancebrokingentry',
            name='exec_code_name',
        ),
        migrations.RemoveField(
            model_name='insurancebrokingentry',
            name='exec_code_no',
        ),
    ]
