# Generated by Django 6.0.4 on 2026-05-19 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_insurancebrokingentry_appln_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancebrokingentry',
            name='branch_assist_code',
        ),
        migrations.RemoveField(
            model_name='insurancebrokingentry',
            name='branch_assist_name',
        ),
        migrations.RemoveField(
            model_name='insurancebrokingentry',
            name='branch_mgr_code',
        ),
        migrations.RemoveField(
            model_name='insurancebrokingentry',
            name='branch_mgr_name',
        ),
        migrations.RemoveField(
            model_name='insurancebrokingentry',
            name='staff_code_name',
        ),
        migrations.RemoveField(
            model_name='insurancebrokingentry',
            name='staff_code_no',
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='branch_assist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_branch_entries', to=settings.AUTH_USER_MODEL, verbose_name='Branch Assistant'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='branch_mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branch_entries', to=settings.AUTH_USER_MODEL, verbose_name='Branch Manager'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_entries', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
    ]
