# Generated by Django 6.0.4 on 2026-05-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_remove_insurancebrokingentry_branch_assist_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='bank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='check_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Check Amount'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='check_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Check Number'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='micr_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='MICR Code'),
        ),
    ]
