# Generated by Django 6.0.4 on 2026-05-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_insurancebrokingentry_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Annual Income'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='dep_email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Depositor Email ID'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='designation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='is_la',
            field=models.BooleanField(default=False, verbose_name='Is LA'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='job_details',
            field=models.CharField(blank=True, max_length=200, verbose_name='Job Details'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='la_email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='LA Email ID'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='la_height_weight',
            field=models.CharField(blank=True, max_length=100, verbose_name='LA Height and Weight'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='la_mother_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='LA Mother Name'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='la_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='LA Name'),
        ),
        migrations.AddField(
            model_name='insurancebrokingentry',
            name='la_phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='LA Phone Number'),
        ),
        migrations.AlterField(
            model_name='insurancebrokingentry',
            name='nominee_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Nominee Date of Birth'),
        ),
        migrations.AlterField(
            model_name='insurancebrokingentry',
            name='nominee_mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='Nominee Mobile Number'),
        ),
        migrations.AlterField(
            model_name='insurancebrokingentry',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nominee Name'),
        ),
    ]
